import type { Metadata } from "next";
import type { Viewport } from 'next'
import { Providers } from "@/app/providers"
import ChatModal from "@/components/Chat/ChatModal";
import { Lexend, Poppins } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}


const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-radial from-slate-800 from-20% to-slate-950" lang="en">
      <body className={`${lexend.className} ${poppins.className} relative`}>
        <Providers>
          <ChatModal />
          {children}
        </Providers>
      </body>
    </html>
  );
}
